AWSTemplateFormatVersion: '2010-09-09'
Description: Webserver EPA-AWS Ubtunu VM GHA
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0e2c8caa4b6378d8c
      KeyName: githubactions
      SecurityGroupIds:
        - sg-0e78abc49a200c373
      SubnetId: subnet-01bb4c11f1b39318e
      Tags:
        - Key: Name
          Value: EPA-AWS

  EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref MyEC2Instance
      AllocationId: eipassoc-0cb48e0aab184b2ea

Outputs:
  InstanceId:
    Description: ID of the created EC2 instance
    Value: !Ref MyEC2Instance
