on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: echo "AWS credentials configured."

      - name: Set Cloudflare Environment Variables
        env:
          S_DOMAIN: ${{ secrets.S_DOMAIN }}
          S_PUBLIC_IP: ${{ secrets.S_PUBLIC_IP }}
          CF_API: ${{ secrets.CF_API }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        run: |
          echo "Cloudflare secrets set in environment"
          echo "S_DOMAIN=$S_DOMAIN"
          echo "S_PUBLIC_IP=$S_PUBLIC_IP"
          echo "CF_API=$CF_API"
          echo "CF_ZONE_ID=$CF_ZONE_ID"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Initialize Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          S_DOMAIN: ${{ secrets.S_DOMAIN }}
          S_PUBLIC_IP: ${{ secrets.S_PUBLIC_IP }}
          CF_API: ${{ secrets.CF_API }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        run: terraform init

      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          S_DOMAIN: ${{ secrets.S_DOMAIN }}
          S_PUBLIC_IP: ${{ secrets.S_PUBLIC_IP }}
          CF_API: ${{ secrets.CF_API }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          S_DOMAIN: ${{ secrets.S_DOMAIN }}
          S_PUBLIC_IP: ${{ secrets.S_PUBLIC_IP }}
          CF_API: ${{ secrets.CF_API }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        run: terraform apply -auto-approve tfplan
