name: Test and Deploy with Bash and Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Edit Cloudflare Variables in Bash Script
      run: |
        echo "Editing variables in cloudflare-dns.sh..."
        sed -i 's/S_DOMAIN/${{ secrets.S_DOMAIN }}/g' ./cloudflare-dns.sh
        sed -i 's/S_PUBLIC_IP/${{ secrets.S_PUBLIC_IP }}/g' ./cloudflare-dns.sh
        sed -i 's/S_CF_API/${{ secrets.CF_API }}/g' ./cloudflare-dns.sh
        sed -i 's/S_CF_ZONE_ID/${{ secrets.CF_ZONE_ID }}/g' ./cloudflare-dns.sh
        cat ./cloudflare-dns.sh  # Confirm the edits

    - name: Edit Certbot Variables in Bash Script
      run: |
        echo "Editing variables in certbot-ssl-install.sh..."
        sed -i 's/S_DOMAIN/${{ secrets.S_DOMAIN }}/g' ./certbot-ssl-install.sh
        sed -i 's/S_EMAIL/${{ secrets.S_EMAIL }}/g' ./certbot-ssl-install.sh
        cat ./certbot-ssl-install.sh  # Confirm the edits

    - name: Transfer and Run Cloudflare Script on VM
      run: |
        echo "Transferring cloudflare-dns.sh to the server..."
        echo "Running cloudflare-dns.sh on the server..."

    - name: Transfer and Run Certbot Script on VM
      run: |
        echo "Transferring certbot-ssl-install.sh to the server..."
        echo "Running certbot-ssl-install.sh on the server..."

    - name: Set Up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        S_DOMAIN: ${{ secrets.S_DOMAIN }}
        S_PUBLIC_IP: ${{ secrets.S_PUBLIC_IP }}
        CF_API: ${{ secrets.CF_API }}
        CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        S_DOMAIN: ${{ secrets.S_DOMAIN }}
        S_PUBLIC_IP: ${{ secrets.S_PUBLIC_IP }}
        CF_API: ${{ secrets.CF_API }}
        CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
      run: terraform apply -auto-approve tfplan
